services:
  postgres:
    image: postgres:15
    container_name: hs_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hs_user
      POSTGRES_PASSWORD: hs_pass
      POSTGRES_DB: hs_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: hs_clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # native TCP
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  adminer:
    image: adminer
    container_name: hs_adminer
    restart: unless-stopped
    ports:
      - "8081:8080"

volumes:
  pgdata:
  clickhouse_data:
