definitions:
  violations.CreateViolationReq:
    properties:
      description:
        type: string
    required:
    - description
    type: object
  violations.ViolationResponse:
    properties:
      description:
        type: string
      id:
        type: integer
      user_id:
        description: <- заменили pgtype.Int4 на int32
        type: integer
    type: object
info:
  contact: {}
paths:
  /violations:
    get:
      description: Get a list of all violations
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/violations.ViolationResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: List all violations
      tags:
      - violations
    post:
      consumes:
      - application/json
      description: Create a new violation for a user
      parameters:
      - description: Violation data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/violations.CreateViolationReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/violations.ViolationResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create a violation
      tags:
      - violations
swagger: "2.0"
